version: '2'
services:
  api:
    build: "./pgi"
    ports:
      - "8080:80"
    environment:
      - DOCKER_HOST=172.17.0.1
    volumes:
      - "./endpoints:/srv/endpoints"
  php:
    build: "./endpoints/php/"
    ports:
      - "9000:9000"
  node:
    build: "./endpoints/node/"
    ports:
      - "10000:10000"
  python:
    build: "./endpoints/python/"
    ports:
      - "11000:11000"
